# Generated by Django 2.2 on 2021-04-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ID',
        ),
    ]
